#!/bin/bash

source check-variables
source check-admin-variables

if [ -z "$1" ]; then
    echo 'no user name given'
    exit
fi
user="$1"
if [ -z "$2" ]; then
    echo 'no password given'
    exit
fi
password="$2"
salt="$RANDOM"
sha1=`echo -n "${password}${salt}" | openssl sha1 | cut -f 2 -d ' '`

rev=`curl "${CLOUDANT_ADMIN_BASE_URL}/_users/org.couchdb.user:${user}" | jq -r '._rev'`
if [[ "${rev}" == "null" ]] ; then
    ifmatch=''
    ifmatchh=''
else
    ifmatch="IF-MATCH: ${rev}"
    ifmatchh='-H'
fi

if curl -sf "${CLOUDANT_ADMIN_BASE_URL}/$user" -X PUT ; then
    echo 'registering...'
else
    echo "Username '${user}' not available."
    exit
fi

curl "${CLOUDANT_ADMIN_BASE_URL}/_users/org.couchdb.user:${user}" -X PUT "${ifmatchh}" "${ifmatch}" -d @- << END1
{
  "salt": "${salt}",
  "password_sha": "${sha1}",
  "roles": [
    "_db_updates"
  ],
  "name": "${user}",
  "type": "user"
}
END1

curl "${CLOUDANT_ADMIN_BASE_URL}/${user}/_security" -X PUT -d @- << END2
{
  "cloudant": {
    "${CLOUDANT_ADMIN_USER}": [
      "_reader",
      "_writer",
      "_admin"
    ],
    "${user}": [
      "_writer",
      "_reader"
    ],
    "nobody": [
      "_reader"
    ]
  }
}
END2

echo 'done'
